openapi: 3.0.0
info:
  title: AceStream API
  version: 1.0.0
servers:
  - url: https://acestream.duckdns.org
paths:
  /acestream:
    get:
      summary: Cerca partite e link AceStream
      description: Restituisce una lista di partite e relativi link AceStream per un termine di ricerca.
      parameters:
        - name: term
          in: query
          required: true
          schema:
            type: string
          description: Termine da cercare (es. nome della squadra)
      responses:
        '200':
          description: Lista risultati AceStream
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    acestream_links:
                      type: array
                      items:
                        type: object
                        properties:
                          language:
                            type: string
                          link:
                            type: string
                    game_title:
                      type: string
                      nullable: true
                    search_term:
                      type: string
                    source:
                      type: string